services:
  backend:
    build:
      context: ./backend_psicologia
    container_name: app_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend_psicologia:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend_psicologia
    container_name: app_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend_psicologia:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sistema_psicologia
      TZ: America/Mexico_City
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  postgres_data_v2: